### ISSUE TITLE
Unable to get authenticated

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [oracle/nosql-dotnet-sdk#8]
````
var config = new NoSQLConfig
            {
                ServiceType = ServiceType.Cloud,
                Region = Region.US_ASHBURN_1,
                Timeout = TimeSpan.FromSeconds(15),
                RetryHandler = new NoSQLRetryHandler
                {
                    MaxRetryAttempts = 20,
                    BaseDelay = TimeSpan.FromSeconds(2),
                    ControlOperationBaseDelay = TimeSpan.FromMinutes(2)
                },
                Compartment = Constants.compartment_id,
                AuthorizationProvider = new IAMAuthorizationProvider(new IAMCredentials()
                {
                    TenantId = Constants.tenancy_id,
                    UserId = Constants.username_id,
                    Fingerprint = Constants.fingerprint,
                    //PrivateKeyFile = Path.GetFullPath("ssh-key-2022-02-09.key")
                    PrivateKeyPEM = Constants.privatekey
                }),
            };



            // This will ensure client is disposed on exit from Main()
            using var client = new NoSQLClient(config);
````

I filled all the required values, with the same values it works withe python. In .net I get the error as below.

```
41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      Oracle.NoSQL.SDK.InvalidAuthorizationException: NotAuthenticated. Request signature is invalid or missing, the credentials information might be expired
      An unhandled exception has occurred while executing the request.
         at Oracle.NoSQL.SDK.Http.Client.ExecuteRequestAsync(Request request, CancellationToken cancellationToken)
         at Oracle.NoSQL.SDK.NoSQLClient.ExecuteValidatedRequestAsync(Request request, CancellationToken cancellationToken)
         at Oracle.NoSQL.SDK.NoSQLClient.ExecuteValidatedRequestAsync(Request request, CancellationToken cancellationToken)
         at Oracle.NoSQL.SDK.NoSQLClient.ExecuteTableDDLAsync(String statement, TableDDLOptions options, CancellationToken cancellationToken)
         at Oracle.NoSQL.SDK.BinaryProtocol.RequestSerializer.ReadAndCheckError(MemoryStream stream)
         at OracleBillingApi.Controllers.BillingController.GetRateCard(String tenancyId) in /Users/ckkolla/Documents/GitLab/ociproject/dotnet/OracleBillingApi/OracleBillingApi/Controllers/BillingController.cs:line 63
         at lambda_method5(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
```

**Comment by mikebrey** [comment]
We will take a look at this .
